[2024-05-16 21:15:31,348: INFO : main: This is the custom logger]
[2024-05-17 01:20:12,534: INFO : main: This is the custom logger]
[2024-05-17 01:41:41,847: INFO : main: This is the custom logger]
[2024-05-17 20:22:07,417: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-17 20:22:07,429: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-17 20:22:29,364: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-17 20:22:29,378: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-17 20:22:29,378: INFO : common: Created Directory at artifacts]
[2024-05-17 20:22:29,378: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-17 20:29:17,183: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-17 20:29:17,188: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-17 20:29:17,191: INFO : common: Created Directory at artifacts]
[2024-05-17 20:29:17,194: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-17 20:31:13,790: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-17 20:31:13,795: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-17 20:31:13,796: INFO : common: Created Directory at artifacts]
[2024-05-17 20:32:46,352: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-17 20:32:46,358: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-17 20:32:46,363: INFO : common: Created Directory at artifacts]
[2024-05-17 20:32:46,364: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-17 20:58:31,486: INFO : main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-05-17 20:58:31,489: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-17 20:58:31,494: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-17 20:58:31,494: INFO : common: Created Directory at artifacts]
[2024-05-17 20:58:31,497: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-17 20:58:31,499: INFO : data_ingestion: Downloading data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-17 20:58:45,093: INFO : data_ingestion: Downloaded data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-17 20:58:46,122: INFO : main: >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2024-05-18 00:38:09,449: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-18 00:38:09,463: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-18 00:38:09,467: INFO : common: Created Directory at artifacts]
[2024-05-18 00:38:09,468: INFO : common: Created Directory at artifacts/prepare_base_model]
[2024-05-18 00:38:15,922: WARNING : saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-18 00:52:14,657: INFO : main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-05-18 00:52:14,657: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-18 00:52:14,657: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-18 00:52:14,657: INFO : common: Created Directory at artifacts]
[2024-05-18 00:52:14,657: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-18 00:52:14,657: INFO : data_ingestion: Downloading data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-18 00:52:19,616: INFO : data_ingestion: Downloaded data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-18 00:52:20,175: INFO : main: >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2024-05-18 00:52:20,175: INFO : main: **********]
[2024-05-18 00:52:20,177: INFO : main: >>>>>>>> Stage Base Model Preparation Stage started <<<<<<<]
[2024-05-18 00:52:20,177: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-18 00:52:20,177: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-18 00:52:20,177: INFO : common: Created Directory at artifacts]
[2024-05-18 00:52:20,177: INFO : common: Created Directory at artifacts/prepare_base_model]
[2024-05-18 00:52:20,655: WARNING : saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-18 00:52:20,946: INFO : main: >>>>>> Stage Base Model Preparation Stage completed <<<<<]
[2024-05-19 21:07:35,942: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 21:07:35,974: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 21:07:35,974: INFO : common: Created Directory at artifacts]
[2024-05-19 21:07:35,984: INFO : common: Created Directory at artifacts\training]
[2024-05-19 21:08:28,053: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 21:08:28,060: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 21:08:28,061: INFO : common: Created Directory at artifacts]
[2024-05-19 21:08:28,067: INFO : common: Created Directory at artifacts\training]
[2024-05-19 21:12:16,416: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 21:12:16,428: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 21:12:16,430: INFO : common: Created Directory at artifacts]
[2024-05-19 21:12:16,430: INFO : common: Created Directory at artifacts\training]
[2024-05-19 21:13:17,604: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 21:13:17,608: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 21:13:17,613: INFO : common: Created Directory at artifacts]
[2024-05-19 21:13:17,617: INFO : common: Created Directory at artifacts\training]
[2024-05-19 21:14:50,377: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 21:14:50,385: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 21:14:50,385: INFO : common: Created Directory at artifacts]
[2024-05-19 21:14:50,385: INFO : common: Created Directory at artifacts\training]
[2024-05-19 21:17:47,596: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 21:17:47,604: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 21:17:47,611: INFO : common: Created Directory at artifacts]
[2024-05-19 21:17:47,612: INFO : common: Created Directory at artifacts\training]
[2024-05-19 23:29:52,339: INFO : main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-05-19 23:29:52,350: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 23:29:52,357: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 23:29:52,357: INFO : common: Created Directory at artifacts]
[2024-05-19 23:29:52,357: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-19 23:29:52,357: INFO : data_ingestion: Downloading data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-19 23:30:16,699: INFO : data_ingestion: Downloaded data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-19 23:30:17,291: INFO : main: >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2024-05-19 23:30:17,291: INFO : main: **********]
[2024-05-19 23:30:17,291: INFO : main: >>>>>>>> Stage Base Model Preparation Stage started <<<<<<<]
[2024-05-19 23:30:17,294: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 23:30:17,294: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 23:30:17,294: INFO : common: Created Directory at artifacts]
[2024-05-19 23:30:17,294: INFO : common: Created Directory at artifacts/prepare_base_model]
[2024-05-19 23:30:17,907: WARNING : saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-19 23:30:18,228: INFO : main: >>>>>> Stage Base Model Preparation Stage completed <<<<<]
[2024-05-19 23:30:18,228: INFO : main: **********]
[2024-05-19 23:30:18,228: INFO : main: >>>>>>>> Stage Model Training started <<<<<<<]
[2024-05-19 23:30:18,233: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-19 23:30:18,236: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-19 23:30:18,236: INFO : common: Created Directory at artifacts]
[2024-05-19 23:30:18,238: INFO : common: Created Directory at artifacts\training]
[2024-05-19 23:31:04,292: INFO : main: >>>>>> Stage Model Training completed <<<<<]
[2024-05-20 00:20:07,878: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:20:07,888: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:27:00,185: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:27:00,192: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:27:52,312: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:27:52,316: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:27:52,318: INFO : common: Created Directory at artifacts]
[2024-05-20 00:28:04,045: INFO : common: JSON file saved at: scores.json]
[2024-05-20 00:28:11,252: WARNING : save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-20 00:28:12,084: INFO : builder_impl: Assets written to: C:\Users\abhis\AppData\Local\Temp\tmpm12_suqt\model\data\model\assets]
[2024-05-20 00:53:51,875: INFO : main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-05-20 00:53:51,875: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:53:51,891: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:53:51,891: INFO : common: Created Directory at artifacts]
[2024-05-20 00:53:51,907: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-20 00:53:51,909: INFO : data_ingestion: Downloading data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-20 00:54:10,114: ERROR : main: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))]
Traceback (most recent call last):
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\urllib3\connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\http\client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    data_ingestion.main()
  File "c:\projects\artificial intelligence\kidney-disease-classification\src\KidneyDiseaseClassifier\pipeline\stage1_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "c:\projects\artificial intelligence\kidney-disease-classification\src\KidneyDiseaseClassifier\components\data_ingestion.py", line 32, in download_file
    raise e
  File "c:\projects\artificial intelligence\kidney-disease-classification\src\KidneyDiseaseClassifier\components\data_ingestion.py", line 27, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2024-05-20 00:54:10,172: INFO : main: **********]
[2024-05-20 00:54:10,172: INFO : main: >>>>>>>> Stage Base Model Preparation Stage started <<<<<<<]
[2024-05-20 00:54:10,180: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:54:10,180: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:54:10,180: INFO : common: Created Directory at artifacts]
[2024-05-20 00:54:10,189: INFO : common: Created Directory at artifacts/prepare_base_model]
[2024-05-20 00:54:11,222: WARNING : saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-20 00:54:11,681: INFO : main: >>>>>> Stage Base Model Preparation Stage completed <<<<<]
[2024-05-20 00:54:11,681: INFO : main: **********]
[2024-05-20 00:54:11,681: INFO : main: >>>>>>>> Stage Model Training started <<<<<<<]
[2024-05-20 00:54:11,681: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:54:11,700: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:54:11,702: INFO : common: Created Directory at artifacts]
[2024-05-20 00:54:11,702: INFO : common: Created Directory at artifacts\training]
[2024-05-20 00:54:12,422: ERROR : main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Dataset']
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    model_trainer.main()
  File "c:\projects\artificial intelligence\kidney-disease-classification\src\KidneyDiseaseClassifier\pipeline\stage3_model_training.py", line 17, in main
    training.train_valid_generator()
  File "c:\projects\artificial intelligence\kidney-disease-classification\src\KidneyDiseaseClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\Dataset'
[2024-05-20 00:55:06,158: INFO : main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-05-20 00:55:06,174: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:55:06,174: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:55:06,174: INFO : common: Created Directory at artifacts]
[2024-05-20 00:55:06,174: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-20 00:55:06,188: INFO : data_ingestion: Downloading data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-20 00:55:50,572: INFO : main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-05-20 00:55:50,572: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:55:50,572: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:55:50,587: INFO : common: Created Directory at artifacts]
[2024-05-20 00:55:50,593: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-20 00:55:50,593: INFO : data_ingestion: Downloading data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-20 00:56:17,302: INFO : data_ingestion: Downloaded data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-20 00:56:18,428: INFO : main: >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2024-05-20 00:56:18,432: INFO : main: **********]
[2024-05-20 00:56:18,432: INFO : main: >>>>>>>> Stage Base Model Preparation Stage started <<<<<<<]
[2024-05-20 00:56:18,437: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:56:18,441: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:56:18,441: INFO : common: Created Directory at artifacts]
[2024-05-20 00:56:18,441: INFO : common: Created Directory at artifacts/prepare_base_model]
[2024-05-20 00:56:19,552: WARNING : saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-20 00:56:20,051: INFO : main: >>>>>> Stage Base Model Preparation Stage completed <<<<<]
[2024-05-20 00:56:20,051: INFO : main: **********]
[2024-05-20 00:56:20,051: INFO : main: >>>>>>>> Stage Model Training started <<<<<<<]
[2024-05-20 00:56:20,058: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 00:56:20,064: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 00:56:20,064: INFO : common: Created Directory at artifacts]
[2024-05-20 00:56:20,068: INFO : common: Created Directory at artifacts\training]
[2024-05-20 01:00:45,413: INFO : main: >>>>>> Stage Model Training completed <<<<<]
[2024-05-20 01:00:45,413: INFO : main: >>>>>> Stage Model Evaluation started <<<<<<]
[2024-05-20 01:00:45,423: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 01:00:45,427: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 01:00:45,430: INFO : common: Created Directory at artifacts]
[2024-05-20 01:00:57,463: INFO : common: JSON file saved at: scores.json]
[2024-05-20 01:01:02,711: WARNING : save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-20 01:01:04,159: INFO : builder_impl: Assets written to: C:\Users\abhis\AppData\Local\Temp\tmp_qhriodc\model\data\model\assets]
[2024-05-20 01:01:23,871: INFO : dir_util: creating C:\Projects\Artificial Intelligence\Kidney-Disease-Classification\mlruns\0\de12cb7f2e8d4b3f8e7af9eec9028d88\artifacts\model\data]
[2024-05-20 01:01:23,871: INFO : dir_util: creating C:\Projects\Artificial Intelligence\Kidney-Disease-Classification\mlruns\0\de12cb7f2e8d4b3f8e7af9eec9028d88\artifacts\model\data\model]
[2024-05-20 01:01:23,885: INFO : dir_util: creating C:\Projects\Artificial Intelligence\Kidney-Disease-Classification\mlruns\0\de12cb7f2e8d4b3f8e7af9eec9028d88\artifacts\model\data\model\assets]
[2024-05-20 01:01:23,892: INFO : dir_util: creating C:\Projects\Artificial Intelligence\Kidney-Disease-Classification\mlruns\0\de12cb7f2e8d4b3f8e7af9eec9028d88\artifacts\model\data\model\variables]
[2024-05-20 01:01:24,132: INFO : main: >>>>>> Stage Model Evaluation completed <<<<<<]
[2024-05-20 01:49:25,408: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 01:49:25,446: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 01:49:25,459: INFO : common: Created Directory at artifacts]
[2024-05-20 01:49:40,931: INFO : common: JSON file saved at: scores.json]
[2024-05-20 01:49:41,426: WARNING : connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /codelikeabhi/Kidney-Disease-Classification.mlflow/api/2.0/mlflow/runs/create]
[2024-05-20 01:49:49,403: WARNING : save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-20 01:49:51,213: INFO : builder_impl: Assets written to: C:\Users\abhis\AppData\Local\Temp\tmpsbh58y0e\model\data\model\assets]
[2024-05-20 11:53:26,251: INFO : stage1_data_ingestion: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-05-20 11:53:26,251: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 11:53:26,267: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 11:53:26,267: INFO : common: Created Directory at artifacts]
[2024-05-20 11:53:26,267: INFO : common: Created Directory at artifacts/data_ingestion]
[2024-05-20 11:53:26,267: INFO : data_ingestion: Downloading data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-20 11:53:59,391: INFO : data_ingestion: Downloaded data from https://drive.google.com/file/d/1mHAjS0aPr8U0Nc-pCpinuF8rbox3G8FO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-20 11:54:00,482: INFO : stage1_data_ingestion: >>>>>> Stage Data Ingestion Stage completed <<<<<<]
[2024-05-20 11:54:23,862: INFO : stage2_prepare_base_model: **********]
[2024-05-20 11:54:23,862: INFO : stage2_prepare_base_model: >>>>>>>> Stage Base Model Preparation Stage started <<<<<<<]
[2024-05-20 11:54:23,869: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 11:54:23,873: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 11:54:23,873: INFO : common: Created Directory at artifacts]
[2024-05-20 11:54:23,878: INFO : common: Created Directory at artifacts/prepare_base_model]
[2024-05-20 11:54:25,127: WARNING : saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-20 11:54:25,636: INFO : stage2_prepare_base_model: >>>>>> Stage Base Model Preparation Stage completed <<<<<]
[2024-05-20 11:54:39,159: INFO : stage3_model_training: **********]
[2024-05-20 11:54:39,159: INFO : stage3_model_training: >>>>>>>> Stage Model Training started <<<<<<<]
[2024-05-20 11:54:39,167: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 11:54:39,177: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 11:54:39,179: INFO : common: Created Directory at artifacts]
[2024-05-20 11:54:39,179: INFO : common: Created Directory at artifacts\training]
[2024-05-20 11:57:25,876: INFO : stage3_model_training: >>>>>> Stage Model Training completed <<<<<]
[2024-05-20 11:57:43,131: INFO : stage4_model_evaluation: **********]
[2024-05-20 11:57:43,131: INFO : stage4_model_evaluation: >>>>>>>> Stage Model Evakuation started <<<<<<<]
[2024-05-20 11:57:43,147: INFO : common: yaml file: config\config.yaml loaded successfully]
[2024-05-20 11:57:43,156: INFO : common: yaml file: params.yaml loaded successfully]
[2024-05-20 11:57:43,156: INFO : common: Created Directory at artifacts]
[2024-05-20 11:57:55,600: INFO : common: JSON file saved at: scores.json]
[2024-05-20 11:58:10,776: WARNING : save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-20 11:58:12,179: INFO : builder_impl: Assets written to: C:\Users\abhis\AppData\Local\Temp\tmp8z61ldi9\model\data\model\assets]
[2024-05-20 11:59:38,158: INFO : stage4_model_evaluation: >>>>>> Stage Model Evakuation completed <<<<<]
[2024-05-20 12:23:08,321: INFO : _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.12.253:8080]
[2024-05-20 12:23:08,321: INFO : _internal: [33mPress CTRL+C to quit[0m]
[2024-05-20 12:23:22,916: INFO : _internal: 127.0.0.1 - - [20/May/2024 12:23:22] "GET / HTTP/1.1" 200 -]
[2024-05-20 12:23:40,049: ERROR : app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 35, in predictionRoute
    result = clApp.classifier.predict()
  File "c:\projects\artificial intelligence\kidney-disease-classification\src\KidneyDiseaseClassifier\pipeline\prediction.py", line 16, in predict
    test_image = image.load_img(imagename, target_size = (224, 224))
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\keras\utils\image_utils.py", line 423, in load_img
    img = pil_image.open(io.BytesIO(f.read()))
  File "C:\Users\abhis\anaconda3\envs\kidney\lib\site-packages\PIL\Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000026001B42D60>
[2024-05-20 12:23:40,067: INFO : _internal: 127.0.0.1 - - [20/May/2024 12:23:40] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-20 12:23:46,592: INFO : _internal: 127.0.0.1 - - [20/May/2024 12:23:46] "GET / HTTP/1.1" 200 -]
[2024-05-20 12:24:11,111: INFO : _internal: 127.0.0.1 - - [20/May/2024 12:24:11] "POST /predict HTTP/1.1" 200 -]
[2024-05-20 12:24:21,920: INFO : _internal: 127.0.0.1 - - [20/May/2024 12:24:21] "POST /predict HTTP/1.1" 200 -]
[2024-05-20 12:25:52,863: INFO : _internal: 127.0.0.1 - - [20/May/2024 12:25:52] "GET / HTTP/1.1" 200 -]
[2024-05-20 12:25:54,393: INFO : _internal: 127.0.0.1 - - [20/May/2024 12:25:54] "GET / HTTP/1.1" 200 -]
